### ISSUE TITLE
Is this project have been abbandoned?

### ISSUE THREAD

**Issue by Helias** [Open-Travelers/OpenCrashWOC#4]
This project seems very interesting, indeed, I added it in my repository Crash Bandicoot Resources where I try to put all these kinds of project together to improve the sharing.

https://github.com/Helias/Crash-Bandicoot-Resources

If you are trying to reproduce the crash 2 engine of the PS1 game there is another repository that is doing it, for the new one, I think there is ReBandicoot but it's a bit old and not maintained.

**Comment by td-9** [comment]
Hi, sorry to only reply now, thanks for including the repo in your list, it's really interesting how carefully you researched and listed every crash bandicoot repos.
the project is not dead, but at a standstill at the moment, I've only been working on it for a few years, it's going very slowly, unfortunately the time I will have to dedicate to this project has decreased exponentially in the last period, so I don't think there will be other updates soon.
the positive thing is that to date the graphics library (called nu3dx) has been finished and other important functions have been completed. I don't know exactly how many functions are left before we can test something, approximately I think around 600 functions (without gameplay functions much less)
I'm looking for collaborators so if you can help promote this project I'd be grateful, thank you

**Comment by Helias** [comment]
Thanks for the answer.
I could promote it a bit, but I made the Crash Bandicoot resources to group all the projects and promote all of them because I am a fan of Crash Bandicoot and open source.

I think that ideally, these three organizations should merge to be stronger

https://github.com/cbhacks
https://github.com/CTR-tools/
https://github.com/Open-Travelers
